#!/bin/zsh

# Profile file: environmental variables etc. are set here after the user shell logs in.

# Adds `~/.local/bin` to $PATH 
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Default programs:
export BROWSER="brave"
export EDITOR="nvim"
export TERMINAL="st"

# Cleaning home folder (~/)
export ZDOTDIR="$HOME/.config/zsh"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export XINITRC="$XDG_CONFIG_HOME/xorg/xinitrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export LESSHISTFILE="-"

# Open installation-unique programs
sh $HOME/.config/profileunique

# Start a X.org server
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
