xcompmgr &
remap &
dwmblocks &
unclutter &
settheme &
xidlehook --not-when-audio --timer 900 'case "$(readlink -f /sbin/init)" in *systemd*) systemctl suspend ;; *) loginctl suspend ;; esac' '' &
exec dwm
